[project]
name = "travelassistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=2.6.1",
    "requests>=2.32.5",
    "tavily-python>=0.7.12",
]
